"""empty message

Revision ID: 8ad8f82f5c86
Revises: c2feb0f52a1c
Create Date: 2024-02-07 19:52:45.057845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad8f82f5c86'
down_revision: Union[str, None] = 'c2feb0f52a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request',
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sender_id', 'receiver_id')
    )
    op.create_table('friends',
    sa.Column('user_left_id', sa.Uuid(), nullable=False),
    sa.Column('user_right_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_left_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_right_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_left_id', 'user_right_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('friend_request')
    # ### end Alembic commands ###
